# Generated by Django 6.1 on 2026-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. AI Engineer', max_length=200)),
                ('period_and_company', models.CharField(help_text='e.g. Freelance / Remote / Various clients - (2025 — Present)', max_length=255)),
                ('description', models.TextField(help_text='Enter bullet points or paragraphs. You can use HTML like or separate lines.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order (smaller numbers appear first).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Journey Entry',
                'verbose_name_plural': 'Journey Entries',
                'ordering': ['order', '-id'],
            },
        ),
    ]
