# Generated by Django 6.1 on 2026-08-18 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. Generative AI', max_length=50)),
                ('slug', models.SlugField(help_text='Filter identifier, e.g. genai, backend, data, other', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-id']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='demo_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='source_url',
        ),
        migrations.AddField(
            model_name='project',
            name='badge_text',
            field=models.CharField(default='Featured', help_text='e.g. Featured, PostgreSQL, Django', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='Enter key feature bullet points on new lines.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Smaller numbers appear first'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='e.g. Python · Streamlit · Gemini API · Pydantic', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.projectcategory'),
        ),
    ]
