# Generated by Django 6.1 on 2026-08-18 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectcategory_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Programming, Backend / Tools & Infra, AI / Generative AI', max_length=100)),
                ('is_wide', models.BooleanField(default=False, help_text="Check this to add the 'skill-card-wide' class for multi-column / wide layout cards.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order of categories (smaller numbers appear first).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Python, Django, RAG, Docker', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order inside the category.')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
