# Generated by Django 6.1 on 2026-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_skillcategory_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. Base, Status, Core stack, Focus', max_length=100)),
                ('value', models.CharField(help_text='e.g. Chattogram, Bangladesh', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order (smaller numbers appear first).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Fact',
                'verbose_name_plural': 'About Facts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='From Django backends to production AI applications.', max_length=255)),
                ('body', models.TextField(help_text='Enter bio paragraphs. Use line breaks to separate paragraphs.')),
                ('is_active', models.BooleanField(default=True, help_text='Select one active profile to show on the main page.')),
            ],
            options={
                'verbose_name': 'About Profile',
                'verbose_name_plural': 'About Profiles',
            },
        ),
    ]
