# Generated by Django 6.1 on 2026-08-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutfact_aboutprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='AI Engineer · Generative AI · Python / Django', max_length=255)),
                ('title', models.CharField(default='Afsan Habib — Building AI-Powered Systems', max_length=255)),
                ('subtitle', models.TextField(default='AI Engineer focused on practical, AI-powered applications — RAG pipelines, LLM tooling, and prompt-driven workflows — built on a backend foundation of Python and Django. I integrate language models into real systems rather than train them from scratch.')),
                ('primary_cta_text', models.CharField(default='View Projects', max_length=100)),
                ('primary_cta_link', models.CharField(default='#projects', max_length=255)),
                ('secondary_cta_text', models.CharField(default='Contact Me', max_length=100)),
                ('secondary_cta_link', models.CharField(default='#contact', max_length=255)),
                ('status_text_1', models.CharField(default='Open to freelance & contract', max_length=100)),
                ('status_link_1', models.URLField(default='https://github.com/AfsanHabib')),
                ('status_text_2', models.CharField(default='Remote — available worldwide', max_length=100)),
                ('status_link_2', models.URLField(default='https://www.linkedin.com/in/afsan-habib-566340215/')),
                ('profile_image', models.ImageField(blank=True, help_text='Upload custom profile photo. If empty, falls back to default static image.', null=True, upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
