# Generated by Django 6.1 on 2026-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Building something with AI?', max_length=255)),
                ('lead_text', models.CharField(default="Let's Work Together", max_length=255)),
                ('email', models.EmailField(default='afsan.uct@gmail.com', max_length=254)),
                ('github_url', models.URLField(default='https://github.com/AfsanHabib')),
                ('availability_title', models.CharField(default='Availability -', max_length=100)),
                ('availability_status', models.CharField(default='Open to freelance & contract', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info Settings',
                'verbose_name_plural': 'Contact Info Settings',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
    ]
